In [6]:
# -*- coding: utf-8 -*-
"""
Created on Mon Oct 17 09:42:17 2022

@author: Usuario
"""
#Configurar como directorio de trabajo D:/Universidad/UNCP/Innovacion de TI/Practicas"
# Tools -> Preferences / Working Directory
# Tools -> Run / Working Directory

import cv2
import numpy as np

bananos=cv2.imread('bananos.jpg')

print(bananos)
# Crear imagen original
cv2.imshow?
cv2.imshow('original',bananos)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


Docstring:
imshow(winname, mat) -> None
.   @brief Displays an image in the specified window.
.   
.   The function imshow displays an image in the specified window. If the window was created with the
.   cv::WINDOW_AUTOSIZE flag, the image is shown with its original size, however it is still limited by the screen resolution.
.   Otherwise, the image is scaled to fit the window. The function may scale the image, depending on its depth:
.   
.   -   If the image is 8-bit unsigned, it is displayed as is.
.   -   If the image is 16-bit unsigned, the pixels are divided by 256. That is, the
.       value range [0,255\*256] is mapped to [0,255].
.   -   If the image is 32-bit or 64-bit floating-point, the pixel values are multiplied by 255. That is, the
.       value range [0,1] is mapped to [0,255].
.   -   32-bit integer images are not processed anymore due to ambiguouty of required transform.
.       Convert to 8-bit unsigned matrix using a custom preprocessing specific to image's context